function y=my_smm_moments_dss_compare_pctile(xopt,replications,innovations,model,params,M,T0,Ti,approx1,pruning,cutoff)
% Inputs:
%   xopt                            vector of parameters in current
%                                   optimization step
%   target                          vector of target data moments
%   replications                    number of simulation replications
%   innovations                     matrix of shocks
%                                   for simulation
%   model                           mat file generated by Levintal's code
%   params                          vector of model parameters
%   M                               matrices of theoretical cross moments of innovations
%   approx1                         order of approximation
%   T0                              initial number of periods in simulations (before innovations occur)
%   Ti                              burn-in number of periods
%   pruning                         pruning dummy
%   cutoff                          percentile cutoff
% Outputs:
%   y                               A vector of simulated_moments

phi_d = exp(xopt(1));
phipar=(xopt(2))^2; %capital adjustment costs
sigma_x = (xopt(3)); %std. innovations to productivity
D1 = (xopt(4));

load('model','symparams');
params(symparams=='phipar') = phipar;
params(symparams=='sigma_x') = sigma_x;
params(symparams=='phi_d') = phi_d;

r_bar = params(symparams=='r_bar');
sigma_r_bar = params(symparams=='sigma_r_bar');
sigma_tb_bar = params(symparams=='sigma_tb_bar');
delta = params(symparams=='delta');
alppha = params(symparams=='alppha');
nu = params(symparams=='nu');
etapar = params(symparams=='etapar');
eta_r = params(symparams=='eta_r');
eta_tb = params(symparams=='eta_tb');

eta=[0 0 0 0 0;0 0 0 0 0;0 0 0 0 0;eta_r 0 0 0 0;0 eta_tb 0 0 0;0 0 0 0 0;0 0 0 0 0;0 0 1 0 0;0 0 0 1 0;0 0 0 0 exp(sigma_x);0 0 0 0 0];

%Recalculate DSS
Hstar = ( (1-alppha)*(alppha/((r_bar)+(delta)))^(alppha/(1-alppha))  )^(1/(etapar-1));
Kstar = Hstar*(alppha/((r_bar)+(delta)))^(1/(1-alppha));
Istar = delta*Kstar;
Ystar = (Kstar^alppha)*Hstar^(1-alppha);
Cstar = D1/(1+(r_bar))-D1+Ystar-Istar;
C_bar = Cstar;
lambdastar = (C_bar)^(-nu);
phistar = lambdastar;

params(symparams=='D_bar') = D1;
params(symparams=='C_bar') = C_bar;

nxss=[D1;log(Kstar);log(Istar);sigma_r_bar;sigma_tb_bar;0;0;0;0;0;0];
nyss=[log(Cstar);log(Hstar);(r_bar);log(lambdastar);log(Ystar);log(phistar);log(Istar);D1];

%Compute up to k-order derivatives
%use Levintal's function solve_dsge.m
algo='vectorize'; % Simple vectorization.
%algo='dlyap'; % Hessenberg-Schur algorithm.
%algo='gensylv'; % Kamenik algorithm
derivs=solve_dsge(model,params,M,eta,nxss,nyss,approx1,algo);

%--------------------------------------------------------------------------
%SSS (for net exports over GDP)
%--------------------------------------------------------------------------
x0=nxss; % start at the steady state

T = 1;
shocks0 = zeros(5,(T0 + (T-1)));

[myt0,mxt0]=simul(x0,shocks0,nyss,nxss,eta,derivs,approx1,0,model);
myt = myt0(:,T0+1:end);
mxt = mxt0(:,T0+1:end);

y_sss = exp(myt(5));
c_sss = exp(myt(1));
i_sss = exp(myt(7));

nx_y_sss = 100*(y_sss - c_sss - i_sss)/y_sss;
%keyboard;

%--------------------------------------------------------------------------
%stochastic simulations
%--------------------------------------------------------------------------

moments = zeros(14,1);
[~,lshocks] = size(innovations(:,:,1));
nexports = zeros(replications,lshocks+1);

for t=1:replications

    shocks = innovations(:,:,t);
    %Choose pruning approach:
    if pruning==1
        [myt_sim,~]=simul_mod_pruning3_dss(mxt,shocks,nyss,nxss,eta,derivs);
        
    else
        [myt_sim,~]=simul(mxt,shocks,nyss,nxss,eta,derivs,approx1,0,model); 
    end

    consumption = exp(myt_sim(1,:));
    output = exp(myt_sim(5,:));
    investment = exp(myt_sim(7,:));
    %keyboard;
    nexports(t,:) = 100*(output-consumption-investment)./output;
    
    myt_sim = myt_sim(:,Ti+1:end);
    myt_sim_exp = exp(myt_sim);
    moments(: ,t) = quarterly_moments_5p_full(myt_sim_exp);

end

%Exclude simulations with large abs. values of net exports, beyond the
%pctile cutoff
nexports = nexports(:,Ti+1:end)';
max_nexports = max(abs(nexports),[],1);
v_netexports = abs(reshape(nexports,[1,replications*(lshocks+1-Ti)]));
moments = moments(:,max_nexports<=prctile(v_netexports,cutoff));

std_y = (moments(1,:));
std_c_y = (moments(2,:));
std_i_y = (moments(3,:));
std_nx_y = moments(4,:);
corr_nxy_y = moments(14,:);

%average moments
m_std_y = mean(std_y)*100;
m_std_c_y = mean(std_c_y);
m_std_i_y = mean(std_i_y);
m_std_nx_y = mean(std_nx_y)*100;

m_corr_nxy_y = mean(corr_nxy_y);

y = [m_std_y;m_std_c_y;m_std_i_y;nx_y_sss;m_std_nx_y;m_corr_nxy_y];