function [ncoeffs,model,T,J,iter]=tpsolvei(coeffs,x0,model,params,paramsi,varargin)
% function [ncoeffs,model,T,J,iter]=tpsolve(coeffs,x0,model,params,c0,nep,P,tolX,tolF,maxiter,varargin)

add_args=1;

if nargin==10+add_args
    type='normal';
    c0=varargin{1};
    nep=varargin{2};
    P=varargin{3};
    tolX=varargin{4};
    tolF=varargin{5};
    maxiter=varargin{6};
    OPTIONS=[];
elseif nargin==11+add_args
    type='normal';
    c0=varargin{1};
    nep=varargin{2};
    P=varargin{3};
    tolX=varargin{4};
    tolF=varargin{5};
    maxiter=varargin{6};
    OPTIONS=varargin{7};
elseif nargin==12+add_args
    type='MS';
    msparams=varargin{1};
    transition=varargin{2};
    c0=varargin{3};
    nep=varargin{4};
    P=varargin{5};
    tolX=varargin{6};
    tolF=varargin{7};
    maxiter=varargin{8};
    OPTIONS=[];
elseif nargin==13+add_args
    type='MS';
    msparams=varargin{1};
    transition=varargin{2};
    c0=varargin{3};
    nep=varargin{4};
    P=varargin{5};
    tolX=varargin{6};
    tolF=varargin{7};
    maxiter=varargin{8};
    OPTIONS=varargin{9};
else
    error('wrong number of input arguments')
end

if isempty(nep) || isempty(P)
    P=1;
    nep=0;
end

if strcmp(type,'normal')
    coeffs=coeffs(:);
    if ~isfield(model,'active_vars')
        if length(coeffs)~=model.n_theta
            error(['The first argument is wrong. The initial guess should be a vector of ' num2str(model.n_theta) ' elements.'])
        end
    else
        if length(coeffs)~=model.n_vars*model.n_b
            error(['The first argument is wrong. The initial guess should be a vector of ' num2str(model.n_vars*model.n_b) ' elements.'])
        end
    end
    x0=x0(:);
    if length(x0)~=model.n_x
        error(['The second argument is wrong. The approximation point should be a vector of ' num2str(model.n_x) ' elements (=the number of state variables).'])
    end
    if ~isstruct(model)
        error('The third argument is wrong. It should be a structure generated by prepare_tp.')
    elseif ~isfield(model,'n_x')
        error('The third argument is wrong. It should be a structure generated by prepare_tp.')
    end

%     params=[params(:);zeros(model.n_logicalparams,1)];

    if length(params)~=model.n_params-model.n_logicalparams-model.n_paramsi
        error(['The fourth argument is wrong. The number of model parameters should be ' num2str(model.n_params) '.'])
    end
    if size(paramsi,1)~=model.n_paramsi
        error(['The number of i-dependent parameters should be ' num2str(model.n_paramsi) '.'])
    end
    
    c0=c0(:);
    if length(c0)~=model.n_x
        error(['The fifth argument is wrong. The center of the approximating polynomial should be a vector of' num2str(model.n_x) ' elements (=the number of state variables).'])
    end
    if size(nep,1)~=model.n_e
        error(['The sixth argument is wrong. It should be a matrix with ' num2str(model.n_e) ' rows (=the number of shocks).'])
    end
    P=P(:);
    if size(nep,2)~=length(P)
        error('The sixth or seventh arguments are wrong. The number of columns in the sixth argument should be equal to the number of elements in the seventh argument.')
    end
    if numel(tolX)~=1 || ~isnumeric(tolX)
        error('The eighth argument should be a numeric scalar')
    end
    if numel(tolF)~=1 || ~isnumeric(tolF)
        error('The ninth argument should be a numeric scalar')
    end
    if numel(maxiter)~=1 || ~isnumeric(maxiter)
        error('The tenth argument should be a numeric scalar')
    end


    msparams=zeros(0,1);
    transition=1;
    if isempty(OPTIONS)
        [ncoeffs,model,T,J,iter]=tpsolveMSi(coeffs,x0,model,params,paramsi,msparams,transition,c0,nep,P,tolX,tolF,maxiter);
    else
        [ncoeffs,model,T,J,iter]=tpsolveMSi(coeffs,x0,model,params,paramsi,msparams,transition,c0,nep,P,tolX,tolF,maxiter,OPTIONS);
    end

else

    if size(coeffs,1)~=model.n_theta || size(coeffs,2)~=model.n_regimes
        message=sprintf(['The first argument is wrong. The initial guess should be a ' num2str(model.n_theta) '-by-' num2str(model.n_regimes) ' matrix.  \nThe number of polynomial coefficients per regime is ' num2str(model.n_theta) ' and the number of regimes is ' num2str(model.n_regimes)'.']);
        error(message);
    end
    x0=x0(:);
    if length(x0)~=model.n_x
        error(['The second argument is wrong. The approximation point should be a vector of' num2str(model.n_x) ' elements (=the number of state variables).'])
    end
    if ~isstruct(model)
        error('The third argument is wrong. It should be a structure generated by prepare_tp.')
    elseif ~isfield(model,'n_x')
        error('The third argument is wrong. It should be a structure generated by prepare_tp.')
    end
%     params=[params(:);zeros(model.n_logicalparams,1)];

    if length(params)~=model.n_params_no_ms-model.n_logicalparams-model.n_paramsi
        error(['The fourth argument is wrong. The number of model parameters should be ' num2str(model.n_params_no_ms) '.'])
    end
    if size(paramsi,1)~=model.n_paramsi
        error(['The number of i-dependent parameters should be ' num2str(model.n_paramsi) '.'])
    end
    
    if isempty(msparams)
        msparams=zeros(0,model.n_regimes);
    end
    if size(msparams,1)~=model.n_msparams || size(msparams,2)~=model.n_regimes
        error(sprintf(['The fifth argument is wrong. It should be a ' num2str(model.n_msparams) '-by-' num2str(model.n_regimes) ' matrix. \nThe number of Markov switching parameters is ' num2str(model.n_msparams) ' and the number of regimes is ' num2str(model.n_regimes) '.']))
    end
    if size(transition,1)~=model.n_regimes || size(transition,2)~=model.n_regimes
        error(['The sixth argument is wrong. The transition matrix should have ' num2str(model.n_regimes) ' rows and columns.'])
    end
    c0=c0(:);
    if length(c0)~=model.n_x
        error(['The seventh argument is wrong. The center of the approximating polynomial should be a vector of' num2str(model.n_x) ' elements (=the number of state variables).'])
    end
    if size(nep,1)~=model.n_e
        error(['The eighth argument is wrong. It should be a matrix with ' num2str(model.n_e) ' rows (=the number of shocks).'])
    end
    P=P(:);
    if size(nep,2)~=length(P)
        error('The eighth or ninth arguments are wrong. The number of columns in the eighth argument should be equal to the number of elements in the ninth argument.')
    end
    if numel(tolX)~=1 || ~isnumeric(tolX)
        error('The tenth argument should be a numeric scalar')
    end
    if numel(tolF)~=1 || ~isnumeric(tolF)
        error('The elevnth argument should be a numeric scalar')
    end
    if numel(maxiter)~=1 || ~isnumeric(maxiter)
        error('The twelfth argument should be a numeric scalar')
    end    
    if isempty(OPTIONS)
        [ncoeffs,model,T,J,iter]=tpsolveMSi(coeffs,x0,model,params,paramsi,msparams,transition,c0,nep,P,tolX,tolF,maxiter);
    else
        [ncoeffs,model,T,J,iter]=tpsolveMSi(coeffs,x0,model,params,paramsi,msparams,transition,c0,nep,P,tolX,tolF,maxiter,OPTIONS);
    end
    
    
end


